version: "3.8"

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--path.rootfs=/host"
    network_mode: host
    pid: host
    ports:
      - 9100:9100
    restart: unless-stopped
    volumes:
      - "/:/host:ro,rslave"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    network_mode: host
    pid: host
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    network_mode: host
    pid: host
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    
